export const dataprofilesContainerTranslations = {
    en: {
        'DATAPROFILES_LOADING': 'Data profile loading',
        'DATAPROFILES_TITLE': 'Data profile',
        'DATAPROFILES_DESCRIPTION': 'Defines data types for all objects on the organization.',
        'DATAPROFILES_PARAMS': 'Parameters',
        'DATAPROFILES_PARAMS_EMPTY': 'There\'s no parameters',
        'DATAPROFILES_EVENTS': 'Events',
        'DATAPROFILES_EVENTS_EMPTY': 'There\'s no events',
        'DATAPROFILES_COMMANDS': 'Commands',
        'DATAPROFILES_COMMANDS_EMPTY': 'There\'s no commands',
        'DATAPROFILES_STATES': 'States',
        'DATAPROFILES_STATES_EMPTY': 'There\'s no states',
        'DATAPROFILES_ACTION_PARAMS_ADD': 'Add parameter',
        'DATAPROFILES_ACTION_EVENTS_ADD': 'Add event',
        'DATAPROFILES_ACTION_COMMANDS_ADD': 'Add command',
        'DATAPROFILES_ACTION_STATES_ADD': 'Add state',
        'DATAPROFILES_ACTION_SAVE': 'Save',
        'DATAPROFILES_ACTION_RESET': 'Reset',
        'DATAPROFILES_RESET_COMMAND_TITLE': 'Remove command',
        'DATAPROFILES_RESET_COMMAND_CONTENT': 'Remove command "{{name}}"?',
        'DATAPROFILES_RESET_EVENT_TITLE': 'Remove event',
        'DATAPROFILES_RESET_EVENT_CONTENT': 'Remove event "{{name}}"?',
        'DATAPROFILES_RESET_PARAMETER_TITLE': 'Remove parameter',
        'DATAPROFILES_RESET_PARAMETER_CONTENT': 'Remove parameter "{{name}}"?',
        'DATAPROFILES_RESET_STATE_TITLE': 'Remove state',
        'DATAPROFILES_RESET_STATE_CONTENT': 'Remove state "{{name}}"?',
        'DATAPROFILES_RESET_DIALOG_TITLE': 'Reset changes',
        'DATAPROFILES_RESET_DIALOG_CONTENT': 'Do you want to reset unsaved changes?',
        'DATAPROFILES_RESET_DIALOG_NO': 'No',
        'DATAPROFILES_RESET_DIALOG_YES': 'Yes',
    },
    ru: {
        'DATAPROFILES_LOADING': 'Загрузка профиля данных',
        'DATAPROFILES_TITLE': 'Профиль данных',
        'DATAPROFILES_DESCRIPTION': 'Определяет типы данных для всех объектов на площадке',
        'DATAPROFILES_PARAMS': 'Параметры',
        'DATAPROFILES_PARAMS_EMPTY': 'Параметры отсутствуют',
        'DATAPROFILES_EVENTS': 'События',
        'DATAPROFILES_EVENTS_EMPTY': 'События отсутствуют',
        'DATAPROFILES_COMMANDS': 'Команды',
        'DATAPROFILES_COMMANDS_EMPTY': 'Команды отсутствуют',
        'DATAPROFILES_STATES': 'Состояния',
        'DATAPROFILES_STATES_EMPTY': 'Состояния отсутствуют',
        'DATAPROFILES_ACTION_PARAMS_ADD': 'Добавить параметр',
        'DATAPROFILES_ACTION_EVENTS_ADD': 'Добавить событие',
        'DATAPROFILES_ACTION_COMMANDS_ADD': 'Добавить команду',
        'DATAPROFILES_ACTION_STATES_ADD': 'Добавить состояние',
        'DATAPROFILES_ACTION_SAVE': 'Сохранить',
        'DATAPROFILES_ACTION_RESET': 'Сбросить',
        'DATAPROFILES_RESET_COMMAND_TITLE': 'Удалить команду',
        'DATAPROFILES_RESET_COMMAND_CONTENT': 'Удалить команду "{{name}}"?',
        'DATAPROFILES_RESET_EVENT_TITLE': 'Удалить событие',
        'DATAPROFILES_RESET_EVENT_CONTENT': 'Удалить событие "{{name}}"?',
        'DATAPROFILES_RESET_PARAMETER_TITLE': 'Удалить параметр',
        'DATAPROFILES_RESET_PARAMETER_CONTENT': 'Удалить параметр "{{name}}"?',
        'DATAPROFILES_RESET_STATE_TITLE': 'Удалить состояние',
        'DATAPROFILES_RESET_STATE_CONTENT': 'Удалить состояние "{{name}}"?',
        'DATAPROFILES_RESET_DIALOG_TITLE': 'Сбросить изменения',
        'DATAPROFILES_RESET_DIALOG_CONTENT': 'Свбросить все несохраненные настройки?',
        'DATAPROFILES_RESET_DIALOG_NO': 'Нет',
        'DATAPROFILES_RESET_DIALOG_YES': 'Да',
    }
};
