export const dataprofilesTranslations = {
    en: {
        'DATAPROFILES_PARAM_SOUND_SIGNAL': 'Sound signal',
        'DATAPROFILES_PARAM_TRAVEL_DISTANCE': 'Travel distance',
        'DATAPROFILES_PARAM_TRAVEL_SPEED': 'Travel speed',
        'DATAPROFILES_PARAM_POWERED': 'Powered',
        'DATAPROFILES_PARAM_FREEZED': 'Freezed',
        'DATAPROFILES_PARAM_IMMOBILE': 'Immobile',
        'DATAPROFILES_PARAM_LOAD_LEVEL': 'Load level',
        'DATAPROFILES_PARAM_GAS_LEVEL': 'Gas level',
        'DATAPROFILES_PARAM_PRESURE': 'Pressure',
        'DATAPROFILES_UNIT_': 'none',
        'DATAPROFILES_UNIT_kg': 'kg',
        'DATAPROFILES_UNIT_ton': 'ton',
        'DATAPROFILES_UNIT_V': 'V',
        'DATAPROFILES_UNIT_l': 'l',
        'DATAPROFILES_UNIT_mV': 'mV',
        'DATAPROFILES_UNIT_A': 'A',
        'DATAPROFILES_UNIT_mA': 'mA',
        'DATAPROFILES_UNIT_C': 'C',
        'DATAPROFILES_UNIT_F': 'F',
        'DATAPROFILES_UNIT_m': 'm',
        'DATAPROFILES_UNIT_m/sec': 'm/sec',
        'DATAPROFILES_UNIT_km': 'km',
        'DATAPROFILES_UNIT_km/h': 'km/h',
        'DATAPROFILES_ALG_CUSTOM': 'Custom algorithm',
        'DATAPROFILES_ALG_SOUND_SIGNAL': 'Send sound signal',
        'DATAPROFILES_ALG_COUNT': 'Counter',
        'DATAPROFILES_ALG_STATISTICS': 'Statistics',
        'DATAPROFILES_ALG_DURATION': 'Duration',
        'DATAPROFILES_ALG_UTILIZATION': 'Utilization',
        'DATAPROFILES_ALG_TRANSPORT': 'Transport',
        'DATAPROFILES_ALG_CONSUMPTION': 'Consumption',
        'DATAPROFILES_ALG_PRESURE': 'Pressure',
        'DATAPROFILES_VALUE_TYPE_FLOAT': 'Float values',
        'DATAPROFILES_VALUE_TYPE_INT': 'Integer values',
        'DATAPROFILES_VALUE_TYPE_BOOL': 'Boolean values',
        'DATAPROFILES_KW_ACTIVATION_BY_COMMAND': 'Activation by command',
        'DATAPROFILES_KW_ACTIVATION_BY_EVENT': 'Activation by event',
        'DATAPROFILES_KW_ACTIVATION_BY_PARAMETER': 'Activation by parameter',
        'DATAPROFILES_KW_ACTIVATION_BY_ON_EVENT': 'On by event',
        'DATAPROFILES_KW_ACTIVATION_BY_OFF_EVENT': 'Off by event',
        'DATAPROFILES_KW_LT': 'less than {{value}}',
        'DATAPROFILES_KW_GT': 'greater than {{value}}',
        'DATAPROFILES_KW_FROM': 'from {{value}}',
        'DATAPROFILES_KW_TO': 'to {{value}}',
        'DATAPROFILES_KW_AND': 'and',
    },
    ru: {
        'DATAPROFILES_PARAM_SOUND_SIGNAL': 'Звуковой сигнал',
        'DATAPROFILES_PARAM_TRAVEL_DISTANCE': 'Пройденное растояние',
        'DATAPROFILES_PARAM_TRAVEL_SPEED': 'Скорость движения',
        'DATAPROFILES_PARAM_POWERED': 'Подключено питание',
        'DATAPROFILES_PARAM_FREEZED': 'Полное замирание',
        'DATAPROFILES_PARAM_IMMOBILE': 'Неподвижность',
        'DATAPROFILES_PARAM_LOAD_LEVEL': 'Уровень загрузки',
        'DATAPROFILES_PARAM_GAS_LEVEL': 'Уровень топлива',
        'DATAPROFILES_PARAM_PRESURE': 'Давление',
        'DATAPROFILES_UNIT_': 'отсутствует',
        'DATAPROFILES_UNIT_kg': 'кг',
        'DATAPROFILES_UNIT_ton': 'т',
        'DATAPROFILES_UNIT_V': 'В',
        'DATAPROFILES_UNIT_l': 'л',
        'DATAPROFILES_UNIT_mV': 'мВ',
        'DATAPROFILES_UNIT_A': 'А',
        'DATAPROFILES_UNIT_mA': 'мА',
        'DATAPROFILES_UNIT_C': 'C',
        'DATAPROFILES_UNIT_F': 'F',
        'DATAPROFILES_UNIT_m': 'м',
        'DATAPROFILES_UNIT_m/sec': 'м/с',
        'DATAPROFILES_UNIT_km': 'км',
        'DATAPROFILES_UNIT_km/h': 'км/ч',
        'DATAPROFILES_ALG_CUSTOM': 'Неопределенный алгоритм',
        'DATAPROFILES_ALG_SOUND_SIGNAL': 'Подача звукового сигнала',
        'DATAPROFILES_ALG_COUNT': 'Счётчик',
        'DATAPROFILES_ALG_STATISTICS': 'Статистика',
        'DATAPROFILES_ALG_DURATION': 'Контроль длительности',
        'DATAPROFILES_ALG_UTILIZATION': 'Контроль использования',
        'DATAPROFILES_ALG_TRANSPORT': 'Контроль транспортировки',
        'DATAPROFILES_ALG_CONSUMPTION': 'Контроль расхода',
        'DATAPROFILES_ALG_PRESURE': 'Контроль давления',
        'DATAPROFILES_VALUE_TYPE_FLOAT': 'Значения с плавающей точкой',
        'DATAPROFILES_VALUE_TYPE_INT': 'Целочисленные значения',
        'DATAPROFILES_VALUE_TYPE_BOOL': 'Логические значения',
        'DATAPROFILES_KW_ACTIVATION_BY_COMMAND': 'Переключение командой',
        'DATAPROFILES_KW_ACTIVATION_BY_EVENT': 'Переключение событием',
        'DATAPROFILES_KW_ACTIVATION_BY_PARAMETER': 'Переключение параметром',
        'DATAPROFILES_KW_ACTIVATION_BY_ON_EVENT': 'Вкл по событию',
        'DATAPROFILES_KW_ACTIVATION_BY_OFF_EVENT': 'Выкл по событию',
        'DATAPROFILES_KW_LT': 'меньше {{value}}',
        'DATAPROFILES_KW_GT': 'больше {{value}}',
        'DATAPROFILES_KW_FROM': 'от {{value}}',
        'DATAPROFILES_KW_TO': 'до {{value}}',
        'DATAPROFILES_KW_AND': 'и',
    }
};
