export const typeDialogTranslations = {
    en: {
        'TYPE_DIALOG_TITLE_COMMAND_ADD': 'Add command',
        'TYPE_DIALOG_TITLE_COMMAND_EDIT': 'Edit command',
        'TYPE_DIALOG_TITLE_COMMAND_VIEW': 'View command',
        'TYPE_DIALOG_TITLE_EVENT_ADD': 'Add event',
        'TYPE_DIALOG_TITLE_EVENT_EDIT': 'Edit event',
        'TYPE_DIALOG_TITLE_EVENT_View': 'View event',
        'TYPE_DIALOG_TITLE_PARAMETER_ADD': 'Add parameter',
        'TYPE_DIALOG_TITLE_PARAMETER_EDIT': 'Edit parameter',
        'TYPE_DIALOG_TITLE_PARAMETER_VIEW': 'View parameter',
        'TYPE_DIALOG_INDEX': 'Index',
        'TYPE_DIALOG_INDEX_REQUIRED': 'Index is required',
        'TYPE_DIALOG_INDEX_EXIST': 'This index already exist',
        'TYPE_DIALOG_INDEX_GT_100': 'Index should be not less than {{value}}',
        'TYPE_DIALOG_NAME': 'Name',
        'TYPE_DIALOG_NAME_REQUIRED': 'Name is required',
        'TYPE_DIALOG_VALUE_TYPE': 'Value type',
        'TYPE_DIALOG_VALUE_TYPE_REQUIRED': 'Value type is required',
        'TYPE_DIALOG_MIN_VALUE': 'Min value',
        'TYPE_DIALOG_MAX_VALUE': 'Max value',
        'TYPE_DIALOG_MIN_RANGE': 'Greater than max',
        'TYPE_DIALOG_MAX_RANGE': 'Less than min',
        'TYPE_DIALOG_UNIT': 'Value unit',
        'TYPE_DIALOG_ALG': 'Algorithm',
        'TYPE_DIALOG_ALG_REQUIRED': 'Algorithm is required',
        'TYPE_DIALOG_ACTION_CLOSE': 'Close',
        'TYPE_DIALOG_ACTION_CANCEL': 'Cancel',
        'TYPE_DIALOG_ACTION_ADD': 'Add',
        'TYPE_DIALOG_ACTION_SAVE': 'Save',
    },
    ru: {
        'TYPE_DIALOG_TITLE_COMMAND_ADD': 'Добавить команду',
        'TYPE_DIALOG_TITLE_COMMAND_EDIT': 'Изменение команды',
        'TYPE_DIALOG_TITLE_COMMAND_VIEW': 'Просмотр команды',
        'TYPE_DIALOG_TITLE_EVENT_ADD': 'Добавить событие',
        'TYPE_DIALOG_TITLE_EVENT_EDIT': 'Изменение события',
        'TYPE_DIALOG_TITLE_EVENT_VIEW': 'Просмотр события',
        'TYPE_DIALOG_TITLE_PARAMETER_ADD': 'Добавить параметр',
        'TYPE_DIALOG_TITLE_PARAMETER_EDIT': 'Изменение параметра',
        'TYPE_DIALOG_TITLE_PARAMETER_VIEW': 'Просмотр параметра',
        'TYPE_DIALOG_INDEX': 'Индекс',
        'TYPE_DIALOG_INDEX_REQUIRED': 'Это поле обязательно',
        'TYPE_DIALOG_INDEX_EXIST': 'Данный индекс уже существует',
        'TYPE_DIALOG_INDEX_GT_100': 'Индекс должен быть не меньше {{value}}',
        'TYPE_DIALOG_NAME': 'Название',
        'TYPE_DIALOG_NAME_REQUIRED': 'Это поле обязательно',
        'TYPE_DIALOG_VALUE_TYPE': 'Тип значений',
        'TYPE_DIALOG_VALUE_TYPE_REQUIRED': 'Это поле обязательно',
        'TYPE_DIALOG_MIN_VALUE': 'Минимальное значение',
        'TYPE_DIALOG_MAX_VALUE': 'Максимальное значение',
        'TYPE_DIALOG_MIN_RANGE': 'Превышает максимум',
        'TYPE_DIALOG_MAX_RANGE': 'Ниже минимума',
        'TYPE_DIALOG_UNIT': 'Единицы измерения',
        'TYPE_DIALOG_ALG': 'Алгоритм',
        'TYPE_DIALOG_ALG_REQUIRED': 'Это поле обязательно',
        'TYPE_DIALOG_ACTION_CLOSE': 'Закрыть',
        'TYPE_DIALOG_ACTION_CANCEL': 'Отменить',
        'TYPE_DIALOG_ACTION_ADD': 'Добавить',
        'TYPE_DIALOG_ACTION_SAVE': 'Сохранить',
    }
};
