export const deviceprofilesDetailsTranslations = {
    en: {
        'DEVICEPROFILES_NAME': 'Name',
        'DEVICEPROFILES_NAME_REQUIRED': 'Name is required',
        'DEVICEPROFILES_BASE': 'Base',
        'DEVICEPROFILES_BASE_REQUIRED': 'Base is required',
        'DEVICEPROFILES_PARAMS': 'Parameters',
        'DEVICEPROFILES_PARAMS_EMPTY': 'There\'s no parameters',
        'DEVICEPROFILES_EVENTS': 'Events',
        'DEVICEPROFILES_EVENTS_EMPTY': 'There\'s no events',
        'DEVICEPROFILES_COMMANDS': 'Commands',
        'DEVICEPROFILES_COMMANDS_EMPTY': 'There\'s no commands',
        'DEVICEPROFILES_CONFIGS': 'Configurations',
        'DEVICEPROFILES_CONFIGS_EMPTY': 'There\'s no configurations',
        'DEVICEPROFILES_BASED_ON': 'Based on {{name}}',
        'DEVICEPROFILES_ACTION_PARAMS_EDIT': 'Edit',
        'DEVICEPROFILES_ACTION_PARAMS_RESET': 'Reset',
        'DEVICEPROFILES_ACTION_PARAMS_DELETE': 'Delete',
        'DEVICEPROFILES_ACTION_PARAMS_ADD': 'Add parameter',
        'DEVICEPROFILES_ACTION_EVENTS_ADD': 'Add event',
        'DEVICEPROFILES_ACTION_COMMANDS_ADD': 'Add command',
        'DEVICEPROFILES_ACTION_CONFIGS_ADD': 'Add configuration',
        'DEVICEPROFILES_ACTION_SAVE': 'Save',
        'DEVICEPROFILES_ACTION_CANCEL': 'Cancel',
        'DEVICEPROFILES_RESET_COMMAND_TITLE': 'Remove command',
        'DEVICEPROFILES_RESET_COMMAND_CONTENT': 'Remove command "{{name}}"?',
        'DEVICEPROFILES_RESET_CONFIGS_TITLE': 'Remove configuration',
        'DEVICEPROFILES_RESET_CONFIGS_CONTENT': 'Remove configuration "{{name}}"?',
        'DEVICEPROFILES_RESET_EVENT_TITLE': 'Remove event',
        'DEVICEPROFILES_RESET_EVENT_CONTENT': 'Remove event "{{name}}"?',
        'DEVICEPROFILES_RESET_PARAMETER_TITLE': 'Remove parameter',
        'DEVICEPROFILES_RESET_PARAMETER_CONTENT': 'Remove parameter "{{name}}"?',
    },
    ru: {
        'DEVICEPROFILES_NAME': 'Имя',
        'DEVICEPROFILES_NAME_REQUIRED': 'Это поле обязательно',
        'DEVICEPROFILES_BASE': 'Модель',
        'DEVICEPROFILES_BASE_REQUIRED': 'Это поле обязательно',
        'DEVICEPROFILES_PARAMS': 'Параметры',
        'DEVICEPROFILES_PARAMS_EMPTY': 'Параметры отсутствуют',
        'DEVICEPROFILES_EVENTS': 'События',
        'DEVICEPROFILES_EVENTS_EMPTY': 'События отсутствуют',
        'DEVICEPROFILES_COMMANDS': 'Команды',
        'DEVICEPROFILES_COMMANDS_EMPTY': 'Команды отсутствуют',
        'DEVICEPROFILES_CONFIGS': 'Конфигурации',
        'DEVICEPROFILES_CONFIGS_EMPTY': 'Конфигурации отсутствуют',
        'DEVICEPROFILES_BASED_ON': 'На основе {{name}}',
        'DEVICEPROFILES_ACTION_PARAMS_EDIT': 'Изменить',
        'DEVICEPROFILES_ACTION_PARAMS_RESET': 'Сбросить',
        'DEVICEPROFILES_ACTION_PARAMS_DELETE': 'Удалить',
        'DEVICEPROFILES_ACTION_PARAMS_ADD': 'Добавить параметр',
        'DEVICEPROFILES_ACTION_EVENTS_ADD': 'Добавить событие',
        'DEVICEPROFILES_ACTION_COMMANDS_ADD': 'Добавить команду',
        'DEVICEPROFILES_ACTION_CONFIGS_ADD': 'Добавить конфигурацию',
        'DEVICEPROFILES_ACTION_SAVE': 'Сохранить',
        'DEVICEPROFILES_ACTION_CANCEL': 'Отменить',
        'DEVICEPROFILES_RESET_COMMAND_TITLE': 'Удалить команду',
        'DEVICEPROFILES_RESET_COMMAND_CONTENT': 'Удалить команду "{{name}}"?',
        'DEVICEPROFILES_RESET_EVENT_TITLE': 'Удалить событие',
        'DEVICEPROFILES_RESET_EVENT_CONTENT': 'Удалить событие "{{name}}"?',
        'DEVICEPROFILES_RESET_PARAMETER_TITLE': 'Удалить параметр',
        'DEVICEPROFILES_RESET_PARAMETER_CONTENT': 'Удалить параметр "{{name}}"?',
        'DEVICEPROFILES_RESET_CONFIGS_TITLE': 'Удалить конфигурацию',
        'DEVICEPROFILES_RESET_CONFIGS_CONTENT': 'Удалить конфигурацию "{{name}}"?',
    }
};
