export const paramDialogTranslations = {
    en: {
        'PARAM_DIALOG_TITLE_COMMAND_ADD': 'Add command',
        'PARAM_DIALOG_TITLE_COMMAND_EDIT': 'Edit command',
        'PARAM_DIALOG_TITLE_COMMAND_VIEW': 'View command',
        'PARAM_DIALOG_TITLE_EVENT_ADD': 'Add event',
        'PARAM_DIALOG_TITLE_EVENT_EDIT': 'Edit event',
        'PARAM_DIALOG_TITLE_EVENT_View': 'View event',
        'PARAM_DIALOG_TITLE_PARAMETER_ADD': 'Add parameter',
        'PARAM_DIALOG_TITLE_PARAMETER_EDIT': 'Edit parameter',
        'PARAM_DIALOG_TITLE_PARAMETER_VIEW': 'View parameter',
        'PARAM_DIALOG_TITLE_CONFIG_ADD': 'Add configuration',
        'PARAM_DIALOG_TITLE_CONFIG_EDIT': 'Edit configuration',
        'PARAM_DIALOG_TITLE_CONFIG_VIEW': 'View configuration',
        'PARAM_DIALOG_INDEX': 'Index',
        'PARAM_DIALOG_INDEX_REQUIRED': 'Index is required',
        'PARAM_DIALOG_INDEX_EXIST': 'This index already exist',
        'PARAM_DIALOG_INDEX_GT_100': 'Index should be not less than {{value}}',
        'PARAM_DIALOG_NAME': 'Name',
        'PARAM_DIALOG_TYPE': 'Displayed on Data profile',
        'PARAM_DIALOG_MIN_VALUE': 'Min value',
        'PARAM_DIALOG_MAX_VALUE': 'Max value',
        'PARAM_DIALOG_MIN_RANGE': 'Greater than max',
        'PARAM_DIALOG_MAX_RANGE': 'Less than min',
        'PARAM_DIALOG_OFFSET': 'Offset',
        'PARAM_DIALOG_SCALE': 'Scale',
        'PARAM_DIALOG_ACTION_CLOSE': 'Close',
        'PARAM_DIALOG_ACTION_CANCEL': 'Cancel',
        'PARAM_DIALOG_ACTION_ADD': 'Add',
        'PARAM_DIALOG_ACTION_SAVE': 'Save',
    },
    ru: {
        'PARAM_DIALOG_TITLE_COMMAND_ADD': 'Добавить команду',
        'PARAM_DIALOG_TITLE_COMMAND_EDIT': 'Изменение команды',
        'PARAM_DIALOG_TITLE_COMMAND_VIEW': 'Просмотр команды',
        'PARAM_DIALOG_TITLE_EVENT_ADD': 'Добавить событие',
        'PARAM_DIALOG_TITLE_EVENT_EDIT': 'Изменение события',
        'PARAM_DIALOG_TITLE_EVENT_VIEW': 'Просмотр события',
        'PARAM_DIALOG_TITLE_PARAMETER_ADD': 'Добавить параметр',
        'PARAM_DIALOG_TITLE_PARAMETER_EDIT': 'Изменение параметра',
        'PARAM_DIALOG_TITLE_PARAMETER_VIEW': 'Просмотр параметра',
        'PARAM_DIALOG_TITLE_CONFIG_ADD': 'Добавить конфигурацию',
        'PARAM_DIALOG_TITLE_CONFIG_EDIT': 'Изменение конфигурации',
        'PARAM_DIALOG_TITLE_CONFIG_VIEW': 'Просмотр конфигурации',
        'PARAM_DIALOG_INDEX': 'Индекс',
        'PARAM_DIALOG_INDEX_REQUIRED': 'Это поле обязательно',
        'PARAM_DIALOG_INDEX_EXIST': 'Данный индекс уже существует',
        'PARAM_DIALOG_INDEX_GT_100': 'Индекс должен быть не меньше {{value}}',
        'PARAM_DIALOG_NAME': 'Название',
        'PARAM_DIALOG_TYPE': 'Отображается на профиль данных',
        'PARAM_DIALOG_MIN_VALUE': 'Минимальное значение',
        'PARAM_DIALOG_MAX_VALUE': 'Максимальное значение',
        'PARAM_DIALOG_MIN_RANGE': 'Превышает максимум',
        'PARAM_DIALOG_MAX_RANGE': 'Ниже минимума',
        'PARAM_DIALOG_OFFSET': 'Смещение',
        'PARAM_DIALOG_SCALE': 'Множитель',
        'PARAM_DIALOG_ACTION_CLOSE': 'Закрыть',
        'PARAM_DIALOG_ACTION_CANCEL': 'Отменить',
        'PARAM_DIALOG_ACTION_ADD': 'Добавить',
        'PARAM_DIALOG_ACTION_SAVE': 'Сохранить',
    }
};
