export const deviceprofilesContainerTranslations = {
    en: {
        'DEVICEPROFILES_LOADING': 'Device profiles loading',
        'DEVICEPROFILES_TITLE': 'Device profiles',
        'DEVICEPROFILES_TITLE_UPDATE': 'Device profile edit',
        'DEVICEPROFILES_TITLE_CREATE': 'Device profile create',
        'DEVICEPROFILES_EMPTY': 'There\'s no device profiles',
        'DEVICEPROFILES_GATEWAY_ANY': 'any connection',
        'DEVICEPROFILES_GATEWAY_LORA': 'LoRa',
        'DEVICEPROFILES_GATEWAY_MQTT': 'MQTT',
        'DEVICEPROFILES_GATEWAY_REST': 'REST',
        'DEVICEPROFILES_GATEWAY_TELTONIKA': 'Teltonika',
        'DEVICEPROFILES_GATEWAY_THROUGH': 'Connection through',
        'DEVICEPROFILES_RESET_DIALOG_TITLE': 'Reset to base',
        'DEVICEPROFILES_RESET_DIALOG_CONTENT': 'Do you want to reset this profile to it base value?',
        'DEVICEPROFILES_DELETE_DIALOG_TITLE': 'Delete device profile',
        'DEVICEPROFILES_DELETE_DIALOG_CONTENT': 'Do you want to delete this profile?',
        'DEVICEPROFILES_CANCEL_DIALOG_TITLE': 'Reset changes',
        'DEVICEPROFILES_CANCEL_DIALOG_CONTENT': 'Do you want to reset unsaved changes?',
        'DEVICEPROFILES_DIALOG_NO': 'No',
        'DEVICEPROFILES_DIALOG_YES': 'Yes',
    },
    ru: {
        'DEVICEPROFILES_LOADING': 'Загрузка профилей устройств',
        'DEVICEPROFILES_TITLE': 'Профили устройств',
        'DEVICEPROFILES_TITLE_UPDATE': 'Редактирования профиля',
        'DEVICEPROFILES_TITLE_CREATE': 'Новый профиль',
        'DEVICEPROFILES_EMPTY': 'Профили устройств отсутствуют',
        'DEVICEPROFILES_GATEWAY_ANY': 'тип связи любой',
        'DEVICEPROFILES_GATEWAY_LORA': 'LoRa',
        'DEVICEPROFILES_GATEWAY_MQTT': 'MQTT',
        'DEVICEPROFILES_GATEWAY_REST': 'REST',
        'DEVICEPROFILES_GATEWAY_TELTONIKA': 'Teltonika',
        'DEVICEPROFILES_GATEWAY_THROUGH': 'Связь через',
        'DEVICEPROFILES_RESET_DIALOG_TITLE': 'Сбросить профиль',
        'DEVICEPROFILES_RESET_DIALOG_CONTENT': 'Сбросить профиль к его базовым значениям?',
        'DEVICEPROFILES_DELETE_DIALOG_TITLE': 'Удалить профиль',
        'DEVICEPROFILES_DELETE_DIALOG_CONTENT': 'Удалить профиль устройств?',
        'DEVICEPROFILES_CANCEL_DIALOG_TITLE': 'Сбросить изменения',
        'DEVICEPROFILES_CANCEL_DIALOG_CONTENT': 'Свбросить все несохраненные настройки?',
        'DEVICEPROFILES_DIALOG_NO': 'Нет',
        'DEVICEPROFILES_DIALOG_YES': 'Да',
    }
};
