export const typeDialogTranslations = {
    en: {
        'STATE_DIALOG_TITLE_ADD': 'Add state',
        'STATE_DIALOG_TITLE_EDIT': 'Edit state',
        'STATE_DIALOG_TITLE_VIEW': 'View state',
        'STATE_DIALOG_INDEX': 'Index',
        'STATE_DIALOG_INDEX_REQUIRED': 'Index is required',
        'STATE_DIALOG_INDEX_EXIST': 'This index already exist',
        'STATE_DIALOG_INDEX_GT_100': 'Index should be not less than {{value}}',
        'STATE_DIALOG_NAME': 'Name',
        'STATE_DIALOG_NAME_REQUIRED': 'Name is required',
        'STATE_DIALOG_SWITCH_PARAMETER': 'Parameter',
        'STATE_DIALOG_SWITCH_EVENT': 'Event',
        'STATE_DIALOG_SWITCH_COMMAND': 'Command',
        'STATE_DIALOG_SWITCH_EVENT_ON': 'On event',
        'STATE_DIALOG_SWITCH_EVENT_OFF': 'Off event',
        'STATE_DIALOG_MIN_VALUE': 'Min value',
        'STATE_DIALOG_MAX_VALUE': 'Max value',
        'STATE_DIALOG_MIN_RANGE': 'Greater than max',
        'STATE_DIALOG_MAX_RANGE': 'Less than min',
        'STATE_DIALOG_ALG': 'Algorithm',
        'STATE_DIALOG_ALG_REQUIRED': 'Algorithm is required',
        'STATE_DIALOG_ACTION_CLOSE': 'Close',
        'STATE_DIALOG_ACTION_CANCEL': 'Cancel',
        'STATE_DIALOG_ACTION_ADD': 'Add',
        'STATE_DIALOG_ACTION_SAVE': 'Save',
    },
    ru: {
        'STATE_DIALOG_TITLE_ADD': 'Добавить состояние',
        'STATE_DIALOG_TITLE_EDIT': 'Изменение команды',
        'STATE_DIALOG_TITLE_VIEW': 'Просмотр команды',
        'STATE_DIALOG_INDEX': 'Индекс',
        'STATE_DIALOG_INDEX_REQUIRED': 'Это поле обязательно',
        'STATE_DIALOG_INDEX_EXIST': 'Данный индекс уже существует',
        'STATE_DIALOG_INDEX_GT_100': 'Индекс должен быть не меньше {{value}}',
        'STATE_DIALOG_NAME': 'Название',
        'STATE_DIALOG_NAME_REQUIRED': 'Это поле обязательно',
        'STATE_DIALOG_SWITCH_PARAMETER': 'Параметр',
        'STATE_DIALOG_SWITCH_EVENT': 'Событие',
        'STATE_DIALOG_SWITCH_COMMAND': 'Команда',
        'STATE_DIALOG_SWITCH_EVENT_ON': 'ВКЛ событие',
        'STATE_DIALOG_SWITCH_EVENT_OFF': 'ВЫКЛ событие',
        'STATE_DIALOG_MIN_VALUE': 'Минимальное значение',
        'STATE_DIALOG_MAX_VALUE': 'Максимальное значение',
        'STATE_DIALOG_MIN_RANGE': 'Превышает максимум',
        'STATE_DIALOG_MAX_RANGE': 'Ниже минимума',
        'STATE_DIALOG_ALG': 'Алгоритм',
        'STATE_DIALOG_ALG_REQUIRED': 'Это поле обязательно',
        'STATE_DIALOG_ACTION_CLOSE': 'Закрыть',
        'STATE_DIALOG_ACTION_CANCEL': 'Отменить',
        'STATE_DIALOG_ACTION_ADD': 'Добавить',
        'STATE_DIALOG_ACTION_SAVE': 'Сохранить',
    }
};
